#!/bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
        # Package removal, not upgrade
        systemctl --no-reload disable kubelet.service > /dev/null 2>&1 || :
        systemctl stop kubelet.service > /dev/null 2>&1 || :
fi
