name: Print Repository Variables
on: [workflow_dispatch]

jobs:
  print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variables
        run: |
          echo "REPO_VARIABLE=${{ env.KUBE_GIT_COMMIT }}"
